# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_students_amount_day', models.IntegerField(default=0)),
                ('active_students_amount_week', models.IntegerField(default=0)),
                ('active_students_amount_month', models.IntegerField(default=0)),
                ('courses_amount', models.IntegerField(default=0)),
                ('data_update', models.DateTimeField(default=datetime.datetime(2017, 5, 30, 8, 2, 40, 757585))),
                ('latitude', models.FloatField(blank=True, default=0)),
                ('longitude', models.FloatField(blank=True, default=0)),
                ('platform_name', models.CharField(blank=True, max_length=255, null=True)),
                ('platform_url', models.URLField(blank=True, null=True)),
                ('secret_token', models.CharField(max_length=255, null=True)),
                ('statistics_level', models.CharField(max_length=255)),
                ('students_per_country', models.TextField()),
            ],
        ),
    ]
