# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20170622_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edxinstallation',
            name='access_token',
            field=models.UUIDField(null=True),
        ),
    ]
