# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20170627_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationstatistics',
            name='statistics_level',
            field=models.CharField(choices=[(b'enthusiast', b'enthusiast'), (b'paranoid', b'paranoid')], default=b'paranoid', max_length=255),
        ),
    ]
