# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_edxinstallation_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edxinstallation',
            name='uid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
