# Serves for configuration of CodeClimate (automated code review for test coverage, complexity, duplication, etc.)
engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD024: # Multiple headers with the same content
        enabled: false # Disabled because of CHANGELOG.md
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.md"
  - "**.py"
exclude_paths:
- "**/vendor/**/*"
- "**/vendored/**/*"
- "web/olga/analytics/create_test_fixture.py"
