version: '2'
services:
  olga:
    container_name: olga
    env_file: ./envs/local.env
    build:
      context: ./web/
      dockerfile: Dockerfile-tests
    command: "python manage.py runserver 0.0.0.0:7000"
    volumes:
      - ./web:/olga
    ports:
      - "7000:7000"
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:9.6
    env_file: ./envs/local.env
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres:
