# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdxInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_token', models.CharField(max_length=255, null=True)),
                ('platform_name', models.CharField(blank=True, max_length=255, null=True)),
                ('platform_url', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, default=0)),
                ('longitude', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_level', models.CharField(max_length=255)),
                ('active_students_amount_day', models.IntegerField(default=0)),
                ('active_students_amount_week', models.IntegerField(default=0)),
                ('active_students_amount_month', models.IntegerField(default=0)),
                ('courses_amount', models.IntegerField(default=0)),
                ('students_per_country', models.TextField()),
                ('data_created_datetime', models.DateTimeField(default=datetime.datetime(2017, 5, 30, 9, 33, 30, 824324))),
                ('edx_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.EdxInstallation')),
            ],
        ),
        migrations.DeleteModel(
            name='DataStorage',
        ),
    ]
