# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20170530_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationstatistics',
            name='data_created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
