# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20170627_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edxinstallation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edxinstallation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
