# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
