# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastorage',
            name='students_per_country',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastorage',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 13, 39, 22, 47776)),
        ),
    ]
