# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastorage',
            old_name='students_quantity',
            new_name='courses_amount',
        ),
        migrations.AddField(
            model_name='datastorage',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datastorage',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datastorage',
            name='platform_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='datastorage',
            name='secret_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='datastorage',
            name='students_amount',
            field=models.IntegerField(default=0),
        ),
    ]
