# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_creator', '0002_auto_20170330_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastorage',
            name='secret_token',
            field=models.UUIDField(null=True),
        ),
    ]
