# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_creator', '0003_auto_20170505_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastorage',
            name='last_data_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 7, 47, 31, 759807)),
        ),
    ]
