# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_creator', '0003_auto_20170330_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastorage',
            name='platform_url',
            field=models.URLField(null=True),
        ),
    ]
