# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_creator', '0005_auto_20170512_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastorage',
            old_name='active_students_amount',
            new_name='active_students_amount_day',
        ),
        migrations.RemoveField(
            model_name='datastorage',
            name='last_data_update',
        ),
        migrations.AddField(
            model_name='datastorage',
            name='active_students_amount_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorage',
            name='active_students_amount_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorage',
            name='data_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 12, 55, 2, 982740)),
        ),
    ]
