# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('analytics', '0001_initial'), ('analytics', '0002_auto_20170530_0933'), ('analytics', '0003_auto_20170612_0932'), ('analytics', '0004_auto_20170615_1451')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdxInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_token', models.CharField(max_length=255, null=True)),
                ('platform_name', models.CharField(blank=True, max_length=255, null=True)),
                ('platform_url', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, default=0)),
                ('longitude', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_level', models.CharField(choices=[(1, b'enthusiast'), (2, b'paranoid')], default=b'paranoid', max_length=255)),
                ('active_students_amount_day', models.IntegerField(default=0)),
                ('active_students_amount_week', models.IntegerField(default=0)),
                ('active_students_amount_month', models.IntegerField(default=0)),
                ('courses_amount', models.IntegerField(default=0)),
                ('students_per_country', models.TextField()),
                ('data_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('edx_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.EdxInstallation')),
            ],
        ),
    ]
